#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use 5.10.0;
use Data::Dumper;


__END__

=head1 NAME

_________: ________________________

=head2 VERSION

0.1

=head1 SYNOPSIS

Quick summary example of using this code

=head1 DESCRIPTION

This is where you do more detailed documentation

=head2 OPTIONS

=over

=item  ______________________

=back

=head1 REQUIREMENTS

Perl 5.10.0 (not tested on earlier versions)
Data::Dumper

=head1 COPYRIGHT AND LICENCE

           Copyright (C)2013 Charlie Harvey

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 
 2 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be 
 useful, but WITHOUT ANY WARRANTY; without even the implied 
 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
 PURPOSE.  See the GNU General Public License for more 
 details.

 You should have received a copy of the GNU General Public 
 License along with this program; if not, write to the Free
 Software Foundation, Inc., 59 Temple Place - Suite 330,
 Boston, MA  02111-1307, USA.
 Also available on line: http://www.gnu.org/copyleft/gpl.html

=head1 SEE ALSO

____________________________

=cut
